feat(Phase-08): Kubernetes configurations for traceroute.
Star-Academy/Summer1403-Devops-Team12 pull request #6
Opened 2024-08-03 13:19 UTC by Alirezaja1384

2024-08-04 09:39 UTC, dkhorasanizadeh requested changes

2024-08-04 09:39 UTC, dkhorasanizadeh commented on Phase-08/api.yaml
> +  # replicas: 3
کامنت‌ها حذف بشه.

2024-08-04 09:39 UTC, dkhorasanizadeh commented on Phase-08/api.yaml
> +apiVersion: v1
فایل سرویس جدا بشه

2024-08-04 09:39 UTC, dkhorasanizadeh commented on Phase-08/api.yaml
> +  # type: LoadBalancer
حذف بشه لطفا

2024-08-04 09:39 UTC, dkhorasanizadeh commented on Phase-08/api.yaml
> +  externalTrafficPolicy: Cluster
چرا این ذکر شده؟

2024-08-04 09:39 UTC, dkhorasanizadeh commented on Phase-08/api.yaml
> +    - port: 80
چرا پورت 80؟

2024-08-04 09:39 UTC, dkhorasanizadeh commented on Phase-08/quota.yaml
ریسورس کوتا رو ادمین کلاستر تعیین می‌کنه و اصلا دلیلی برای نوشتنش بوسیله شما نیست.

2024-08-04 09:39 UTC, dkhorasanizadeh commented on Phase-08/storage.yaml
اگر PVC دارید خود کلاستر با استفاده از استورج کلسی که داره PV میسازه و نیازی به ساخت دستی PV نیست.

2024-08-04 09:39 UTC, dkhorasanizadeh commented on Phase-08/redis.yaml
> +  storageClassName: standard # Don't know if this is a good idea but fixes the replace issue
آوردن اسم استورج کلس داخل PVC به طور کلی چندان خوب نیست به خاطر اینکه با جابجایی منیفست از یک کلاستر به کلاستر دیگه ممکنه SC کلاستر اول رو تو کلاستر دوم نداشته باشیم و ریسورسمون پرتابل بودنش رو از دست بده. معمولا تو کلاسترهامون یک SC دیفالت داریم و از همون استفاده می‌کنیم مگر اینکه نیاز به تغییر باشه.

2024-08-04 09:39 UTC, dkhorasanizadeh commented on Phase-08/redis.yaml
> +  volumeMode: Filesystem
چرا فیلدی که به صورت دیفالت همینه دوباره ست شده؟

2024-08-04 09:46 UTC, msm1984 commented on Phase-08/redis.yaml
> +  storageClassName: standard # Don't know if this is a good idea but fixes the replace issue
این وقتی من داشتم تست میکردم اگر SC رو set نمیکردم pvc نمیتونست با pv که تعریف کرده بودم bind بشه و همش تو حالت pending میموند

2024-08-04 09:49 UTC, msm1984 commented on Phase-08/api.yaml
> +    - port: 80
این گویا اشتباه شده باید 8080 باشه

2024-08-05 08:39 UTC, closed without merging

2024-08-05 09:05 UTC, Alirezaja1384 commented on Phase-08/api.yaml
> +    - port: 80
معذرت که PR ها بسته شدن. یه اشتباهی کردم که باعث شد history گیت به هم بریزه. ایجا پورت رو گذاشتم که اگر pod دیگه ای بخواد  با api صحبت کنه راحت با پورت ۸۰ این سرویس کار کنه. یه جورایی براش مهم نباشه داخل اون کانتینر چه خبره و api روی چه پورتی کار میکنه. نمیدونم کار درستی بوده یا نه.

2024-08-05 09:09 UTC, Alirezaja1384 commented on Phase-08/api.yaml
> +  externalTrafficPolicy: Cluster
فکر میکنم از موقعی که میخواستم LoadBalancer رو تست کنم مونده. پاکش میکنم. ممنون.

2024-08-05 09:09 UTC, alirezaja1384 commented on Phase-08/quota.yaml
حذفشون میکنم.

2024-08-05 09:13 UTC, Alirezaja1384 commented on Phase-08/storage.yaml
PV رو حذف میکنم

2024-08-05 09:54 UTC, Alirezaja1384 commented on Phase-08/redis.yaml
> +  volumeMode: Filesystem
فکر کنم از [نمونه‌ی داک کوبر](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims) برداشتم. حذف شد.

2024-08-05 09:55 UTC, alirezaja1384 commented on Phase-08/redis.yaml
> +  storageClassName: standard # Don't know if this is a good idea but fixes the replace issue
حذف شد. ممنون.

2024-08-05 10:30 UTC, dkhorasanizadeh commented on Phase-08/api.yaml
> +    - port: 80
نیازی به این نیست. اگر جای دیگری بخواد با این سرویس ارتباط برقرار کنه به صورت رانتایم آدرسش رو ورودی میگیره و طبیعتا پورت هم میتونه بخشی از اون آدرس باشه.

2024-08-05 11:22 UTC, Alirezaja1384 commented on Phase-08/api.yaml
> +    - port: 80
خب اینکار باعث نمیشه سرویس ها وابستگیشون به موارد داخلی همدیگه کمتر بشه؟ اگه ما port رو روی یه پورت استاندارد مثل 80  بذاریم میتونیم پورت اپی که داخل کانتینتر اجرا میشه رو بدون دردسر عوض کنیم و بقیه اپ ها اصلا خبردار هم نشن 🤔